### ISSUE TITLE
Runtime Errors while including ".so" files. Doesn't work on android

### ISSUE THREAD

**Issue by SangameswaranRS** [marykdb/rocksdb-android#1]
in rocksdb, .so files are packaged along the jar file.

usually in Rocks DB's native loader, .so files are copied from the jar to a tmp dir and System.loadLib is called on that particular temp dir.

It works without a problem on JVM runtimes.
But when it comes to ART, *.so files are removed when building the APK. (not pro guard, it seems like a default behaviour)

So regardless of this wrapper, RocksDB's native loader won't be able to find the required .so files.

**Comment by tadfisher** [comment]
I don't believe it's correct that .so files are stripped from JARs, but RocksJava's loading mechanism probably doesn't work on newer Android versions that prevent loading executable code from writable directories on disk.

The correct thing to do is to produce an AAR artifact, not a plain JAR. The install process automatically unpacks native libraries and enables the use of `System.loadLibrary` without any manual work.

**Comment by jurmous** [comment]
I just noticed I missed this issue for years since I was not watching this repo.. Sorry.. 
The issue should be fixed now in version 8.0.0
